/**
 * Mega pixel image rendering library for iOS6 Safari
 *
 * Fixes iOS6 Safari's image file rendering issue for large size image (over mega-pixel),
 * which causes unexpected subsampling when drawing it in canvas.
 * By using this library, you can safely render the image with proper stretching.
 *
 * Copyright (c) 2012 Shinichi Tomita <shinichi.tomita@gmail.com>
 * Released under the MIT license
 */

(function(){function e(e){var t=e.naturalWidth,n=e.naturalHeight;if(t*n>1048576){var r=document.createElement("canvas");r.width=r.height=1;var i=r.getContext("2d");return i.drawImage(e,-t+1,0),i.getImageData(0,0,1,1).data[3]===0}return!1}function t(e,t,n){var r=document.createElement("canvas");r.width=1,r.height=n;var i=r.getContext("2d");i.drawImage(e,0,0);var s=i.getImageData(0,0,1,n).data,o=0,u=n,a=n;while(a>o){var f=s[(a-1)*4+3];f===0?u=a:o=a,a=u+o>>1}var l=a/n;return l===0?1:l}function n(e,t,n){var i=document.createElement("canvas");return r(e,i,t,n),i.toDataURL("image/jpeg",t.quality||.8)}function r(n,r,s,o){var u=n.naturalWidth,a=n.naturalHeight;if(!(u+a))return;var f=s.width,l=s.height,c=r.getContext("2d");c.save(),i(r,c,f,l,s.orientation);var h=e(n);h&&(u/=2,a/=2);var p=1024,d=document.createElement("canvas");d.width=d.height=p;var v=d.getContext("2d"),m=o?t(n,u,a):1,g=Math.ceil(p*f/u),y=Math.ceil(p*l/a/m),b=0,w=0;while(b<a){var E=0,S=0;while(E<u)v.clearRect(0,0,p,p),v.drawImage(n,-E,-b),c.drawImage(d,0,0,p,p,S,w,g,y),E+=p,S+=g;b+=p,w+=y}c.restore(),d=v=null}function i(e,t,n,r,i){switch(i){case 5:case 6:case 7:case 8:e.width=r,e.height=n;break;default:e.width=n,e.height=r}switch(i){case 2:t.translate(n,0),t.scale(-1,1);break;case 3:t.translate(n,r),t.rotate(Math.PI);break;case 4:t.translate(0,r),t.scale(1,-1);break;case 5:t.rotate(.5*Math.PI),t.scale(1,-1);break;case 6:t.rotate(.5*Math.PI),t.translate(0,-r);break;case 7:t.rotate(.5*Math.PI),t.translate(n,-r),t.scale(-1,1);break;case 8:t.rotate(-0.5*Math.PI),t.translate(-n,0);break;default:}}function o(e){if(window.Blob&&e instanceof Blob){if(!s)throw Error("No createObjectURL function found to create blob url");var t=new Image;t.src=s.createObjectURL(e),this.blob=e,e=t}if(!e.naturalWidth&&!e.naturalHeight){var n=this;e.onload=e.onerror=function(){var e=n.imageLoadListeners;if(e){n.imageLoadListeners=null;for(var t=0,r=e.length;t<r;t++)e[t]()}},this.imageLoadListeners=[]}this.srcImage=e}var s=window.URL&&window.URL.createObjectURL?window.URL:window.webkitURL&&window.webkitURL.createObjectURL?window.webkitURL:null;o.prototype.render=function(e,t,i){if(this.imageLoadListeners){var o=this;this.imageLoadListeners.push(function(){o.render(e,t,i)});return}t=t||{};var u=this.srcImage.naturalWidth,a=this.srcImage.naturalHeight,f=t.width,l=t.height,c=t.maxWidth,h=t.maxHeight,p=!this.blob||this.blob.type==="image/jpeg";f&&!l?l=a*f/u<<0:l&&!f?f=u*l/a<<0:(f=u,l=a),c&&f>c&&(f=c,l=a*f/u<<0),h&&l>h&&(l=h,f=u*l/a<<0);var d={width:f,height:l};for(var v in t)d[v]=t[v];var m=e.tagName.toLowerCase();m==="img"?e.src=n(this.srcImage,d,p):m==="canvas"&&r(this.srcImage,e,d,p),typeof this.onrender=="function"&&this.onrender(e),i&&i(),this.blob&&(this.blob=null,s.revokeObjectURL(this.srcImage.src))},typeof define=="function"&&define.amd?define([],function(){return o}):typeof exports=="object"?module.exports=o:this.MegaPixImage=o})();